version: '3.8'

services:
  mongo:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - "27017:27017"

  renetti:
    image: renetti:prod
    deploy:
      replicas: 1
    depends_on:
      - 'mongo'
    secrets:
      - source: renetti
        target: renetti
        mode: 0444

secrets:
  renetti:
    file: ./renetti.env
